"""crear_tabla_grupos_y_relacion_usuario

Revision ID: 733bd683c2dd
Revises: 
Create Date: 2026-06-01 19:13:08.866476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733bd683c2dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Creamos la tabla de grupos manualmente para asegurar que producción la tenga
    # op.create_table(
    #     'grupos',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('nombre', sa.String(length=100), nullable=False),
    #     sa.Column('descripcion', sa.String(length=255), nullable=True),
    #     sa.Column('creado_en', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    #     sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    # op.create_index(op.f('ix_grupos_nombre'), 'grupos', ['nombre'], unique=True)

    # 2. Modificaciones auto-detectadas
    # op.drop_index('ix_cambiosClientes_id', table_name='cambiosclientes')
    # op.create_index(op.f('ix_cambiosclientes_id'), 'cambiosclientes', ['id'], unique=False)
    # op.drop_index('sku', table_name='productos')
    # op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=True)
    op.add_column('usuarios', sa.Column('grupo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'grupos', ['grupo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'grupo_id')
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.create_index('sku', 'productos', ['sku'], unique=True)
    op.drop_index(op.f('ix_cambiosclientes_id'), table_name='cambiosclientes')
    op.create_index('ix_cambiosClientes_id', 'cambiosclientes', ['id'], unique=False)
    
    # Eliminamos la tabla grupos al hacer rollback
    op.drop_index(op.f('ix_grupos_nombre'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_table('grupos')
    # ### end Alembic commands ###
